name : Build and Test
on:
  push:
      branches:
      -main
  pull_requests:
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      -name: Checkout code
       uses: actions/checkout@2
      -name: install Node.js 14.x
       uses: actions/setup-node@v2
       with:
        node-version: 14.x
        cache: npm
      -name: Install dependancies
       run : npm install
      -name: Run unit tests
       run: npm test
        
